baseurl: 'https://psy6983.brainhackmtl.org'
title: 'PSY6983'
theme: hugo-universal-theme
defaultContentLanguage: en
defaultContentLanguageInSubdir: FALSE

outputFormats:
  Calendar:
    mediaType: text/calendar

languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    taxonomies:
      tag: tags
      category: categories
      name: names
    enableGitInfo: TRUE
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: Schedule
          name: Schedule
          url: /schedule/
          weight: 2
        - identifier: Projects
          name: Projects
          url: /project/
          weight: 3
        - identifier: Weeks
          name: Weeks
          url: /weeks/
          weight: 4
        - identifier: Locations
          name: Locations
          url: /locations/
          weight: 5
        - identifier: Register
          name: Register
          url: /register/
          weight: 6
        - identifier: Modules
          name: Modules
          url: /modules/
          weight: 6


      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/brainhackMTL/school/'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 3
          name: Twitter
          url: 'http://twitter.com/brainhackMTL'
          pre: <i class='fab fa-2x fa-twitter'></i>
        - weight: 4
          name: Email
          url: 'mailto:emilie.dessureault@criugm.qc.ca'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      outputFormats:
        Calendar:
          mediaType: text/calendar
      viewMorePostLink: /blog/
      author:
      defaultKeywords:
        - BrainHack
        - Neuroscience
      mainSections:
        - blog
      defaultDescription: Brainhack School
      facebook_site: ''
      twitter_site: BrainhackMTL
      default_sharing_image: img/brainhackSchool.jpg
      googleMapsApiKey:
      style: green
      email:
      contact_form_ajax: false
      about_us: >-
        <p>Fundamentals and project in neural data science.</p>
      copyright: 'Copyright (c) 2020, BrainHack School; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>BrainHack School</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: true
      instructors:
        enable: true
      features:
        enable: false
      testimonials:
        enable: true
        title: Why PSY6983?
        subtitle: >-
          Coding and other data science skills are much better acquired and
          solidified through practice. After a one week bootcamp, most of the
          PSY6983 training consists of open and collaborative work on a project of
          your choice.
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Project-based, transdisciplinary training'
        subtitle: 'Neuroscience, Statistical Modelling and Computer Science'
        link_url: https://www.youtube.com/watch?v=z10TgOf08s0&list=PLfqBzCl5BL3-m9BH5qi4u4QzoJBC8Ze72
        link_text: "You can watch all the 2020 lectures on youtube"
        video: https://www.youtube.com/embed/PTYs_JFKsHI?list=PLfqBzCl5BL3-m9BH5qi4u4QzoJBC8Ze72
      clients:
        enable: true
        title: Partner institutions
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: false
        text: "**:computer: :brain: Contact <simexp.lab@gmail.com> to register! :brain: :computer:**: "


  fr:
    languageCode: fr
    languageName: Français
    contentDir: content/fr
    title: 'PSY6983'
    weight: 2
    taxonomies:
      tag: tags
      category: categories
      name: names
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: Schedule
          name: Schedule
          url: /schedule/
          weight: 2
        - identifier: Projects
          name: Projects
          url: /project/
          weight: 3
        - identifier: Weeks
          name: Weeks
          url: /weeks/
          weight: 4
        - identifier: Locations
          name: Locations
          url: /locations/
          weight: 5
        - identifier: Register
          name: Register
          url: /register/
          weight: 6

      topbar:
        - weight: 1
          name: GitHub
          url: 'https://github.com/brainhackMTL/school/'
          pre: <i class='fab fa-2x fa-github'></i>
        - weight: 3
          name: Twitter
          url: 'http://twitter.com/brainhackMTL'
          pre: <i class='fab fa-2x fa-twitter'></i>
        - weight: 4
          name: Email
          url: 'mailto:info@bhs.com'
          pre: <i class='fas fa-2x fa-envelope'></i>

    params:
      viewMorePostLink: /blog/
      author:
      defaultKeywords:
        - Science des données
        - Neuroscience
      mainSections:
        - blog
      defaultDescription:
      facebook_site: ''
      twitter_site: BrainhackMTL
      default_sharing_image: img/sharing-default.png
      googleMapsApiKey:
      style: green
      email: pierre.bellec@gmail.com
      contact_form_ajax: false
      about_us: >-
        <p>Apprentissage basé projet en sciences des données neuronales.</p>
      copyright: 'Copyright (c) 2021, BrainHack School; all rights reserved.'
      date_format: 'January 2, 2006'
      logo: img/logo_brainhack.png
      logo_small: img/logo-small.png
      address: |-
        <p class="text-uppercase"><strong>PSY6983</strong>
                <br>
                <br>Montreal
                <br>
                <strong>Canada</strong>
              </p>

      latitude: '45.50884'
      longitude: '-73.58781'

      widgets:
        categories: true
        tags: true
        search: true
      carousel:
        enable: true
      instructors:
        enable: true
      features:
        enable: false
      testimonials:
        enable: true
        title: Pourquoi PSY6983?
        subtitle: >-
          L'apprentissage par la pratique est très bien adapté pour la programmation et les autres compétences utiles en sciences des données. Après une semaine intensive de présentations,
          la majorité de la formation PSY6983 consiste en un projet de votre choix, réalisé de votre de manière ouverte et collaborative.
      see_more:
        enable: true
        icon: far fa-file-alt
        title: 'Formation transdisciplinaire axée sur les projets'
        subtitle: 'Neurosciences, Modélisation statistique et Sciences informatiques'
        link_url: https://www.youtube.com/watch?v=z10TgOf08s0&list=PLfqBzCl5BL3-m9BH5qi4u4QzoJBC8Ze72
        link_text: "Vous pouvez accéder à toutes les présentations 2020 sur youtube"
        video: https://www.youtube.com/embed/PTYs_JFKsHI?list=PLfqBzCl5BL3-m9BH5qi4u4QzoJBC8Ze72?t=6
      clients:
        enable: true
        title: Institutions partenaires
        subtitle: ''
      recent_posts:
        enable: false
        title: Project gallery
        subtitle: A selection of projects from our students
      topbar:
        enable: true
        text: "**:computer: :brain: Contactez <simexp.lab@gmail.com> pour vous inscrire! :brain: :computer:**"

Permalinks:
  blog: '/blog/:year/:month/:day/:filename/'

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3


disqusShortname: ''
googleAnalytics: ''
paginate: 10
